#!/usr/bin/env ruby

site "http://community.opscode.com/api/v1"

cookbook "chef-solo-search", :git => "https://github.com/TylerRick/chef-solo-search"
cookbook "apt"
cookbook "users"
cookbook "sudo"
cookbook "build-essential"
cookbook "iptables"
cookbook "openssh"
cookbook "runit"
# cookbook "zsh"
cookbook "ntp"
cookbook "vim"
cookbook "git"
# cookbook "ssh_known_hosts"
cookbook "screen"
cookbook "hostname"
# cookbook "monit", :git => "https://github.com/phlipper/chef-monit"
cookbook "fail2ban"
cookbook "logrotate"

cookbook "ruby_build", :git => "https://github.com/fnichol/chef-ruby_build"
cookbook "rbenv", :git => "https://github.com/fnichol/chef-rbenv"
cookbook "apache2"
# cookbook "nginx"

cookbook "mysql"
cookbook "database"

# cookbook "application"

# cookbook 'chef-client'
# cookbook 'apache2', '>= 1.0.0'
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'
# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
